
/*******************************************************************************
* generated by lcd-image-converter rev.aff2edd from 2018-09-09 14:13:46 +0300
* font
* filename: /home/STM32/Projects/bikecomp-f103/files/bikecomp-icons.xml
* name: bikecomp-icons
* family: Liberation Sans
* size: 14
* style: Bold
* included characters: \x0000\x0001\x0002
* antialiasing: no
* type: proportional
* encoding: UTF-16
* unicode bom: no
*
* preset name: ampcontrol-f103-icons-rle3
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: yes
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: no
* bits per pixel: 1
*
* preprocess:
*  main scan direction: left_to_right
*  line scan direction: backward
*  inverse: yes
*******************************************************************************/

/*
typedef struct {
    const uint8_t *data;
    uint16_t width;
    uint16_t height;
    uint16_t size;
    uint8_t rle;
} tImage;

typedef struct {
    int32_t code;
    const tImage *image;
} tChar;

typedef struct {
    uint16_t length;
    const tChar *chars;
} tFont;
*/

#define no  0x00
#define yes 0x01

#include <stdint.h>

#include "fonts.h"




#if (0x0 == 0x0)
static const uint8_t image_data_bikecompicons_0x0000[35] = {
    // ∙∙∙∙∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙████∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙████∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙██████∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙██████∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙████████∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙████████∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙██████████∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙██████████∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙████████████∙∙∙∙∙∙
    // ∙∙∙∙∙∙████████████∙∙∙∙∙∙
    // ∙∙∙∙∙██████████████∙∙∙∙∙
    // ∙∙∙∙∙██████████████∙∙∙∙∙
    // ∙∙∙∙████████████████∙∙∙∙
    // ∙∙∙∙████████████████∙∙∙∙
    // ∙∙∙██████████████████∙∙∙
    // ∙∙∙██████████████████∙∙∙
    // ∙∙████████████████████∙∙
    // ∙∙████████████████████∙∙
    // ∙██████████████████████∙
    // ∙██████████████████████∙
    // ████████████████████████
    // ████████████████████████
    0x08, 0x00, 0xf8, 0xc0, 0xf0, 0xfc, 0xff, 0xff, 0xfc, 0xf0, 0xc0, 0x0c, 0x00, 0xfd, 0xc0, 0xf0, 0xfc, 0x0a, 0xff, 0xfd, 0xfc, 0xf0, 0xc0, 0x04, 0x00, 0xfd, 0xc0, 0xf0, 0xfc, 0x12, 0xff, 0xfd, 0xfc, 0xf0, 0xc0
};
static const tImage bikecompicons_0x0000 = { image_data_bikecompicons_0x0000, 24, 24, 35, yes};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_bikecompicons_0x0001[35] = {
    // ████████████████████████
    // ████████████████████████
    // ∙██████████████████████∙
    // ∙██████████████████████∙
    // ∙∙████████████████████∙∙
    // ∙∙████████████████████∙∙
    // ∙∙∙██████████████████∙∙∙
    // ∙∙∙██████████████████∙∙∙
    // ∙∙∙∙████████████████∙∙∙∙
    // ∙∙∙∙████████████████∙∙∙∙
    // ∙∙∙∙∙██████████████∙∙∙∙∙
    // ∙∙∙∙∙██████████████∙∙∙∙∙
    // ∙∙∙∙∙∙████████████∙∙∙∙∙∙
    // ∙∙∙∙∙∙████████████∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙██████████∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙██████████∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙████████∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙████████∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙██████∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙██████∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙████∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙████∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙
    0xfd, 0x03, 0x0f, 0x3f, 0x12, 0xff, 0xfd, 0x3f, 0x0f, 0x03, 0x04, 0x00, 0xfd, 0x03, 0x0f, 0x3f, 0x0a, 0xff, 0xfd, 0x3f, 0x0f, 0x03, 0x0c, 0x00, 0xf8, 0x03, 0x0f, 0x3f, 0xff, 0xff, 0x3f, 0x0f, 0x03, 0x08, 0x00
};
static const tImage bikecompicons_0x0001 = { image_data_bikecompicons_0x0001, 24, 24, 35, yes};
#endif

#if (0x00001 == 0x0)
static const uint8_t image_data_bikecompicons_0x0002[35] = {
    // ████████████████████████
    // ████████████████████████
    // ∙██████████████████████∙
    // ∙██████████████████████∙
    // ∙∙████████████████████∙∙
    // ∙∙████████████████████∙∙
    // ∙∙∙██████████████████∙∙∙
    // ∙∙∙██████████████████∙∙∙
    // ∙∙∙∙████████████████∙∙∙∙
    // ∙∙∙∙████████████████∙∙∙∙
    // ∙∙∙∙∙██████████████∙∙∙∙∙
    // ∙∙∙∙∙██████████████∙∙∙∙∙
    // ∙∙∙∙∙∙████████████∙∙∙∙∙∙
    // ∙∙∙∙∙∙████████████∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙██████████∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙██████████∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙████████∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙████████∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙██████∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙██████∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙████∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙████∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙██∙∙∙∙∙∙∙∙∙∙∙
    0xfd, 0x03, 0x0f, 0x3f, 0x12, 0xff, 0xfd, 0x3f, 0x0f, 0x03, 0x04, 0x00, 0xfd, 0x03, 0x0f, 0x3f, 0x0a, 0xff, 0xfd, 0x3f, 0x0f, 0x03, 0x0c, 0x00, 0xf8, 0x03, 0x0f, 0x3f, 0xff, 0xff, 0x3f, 0x0f, 0x03, 0x08, 0x00
};
static const tImage bikecompicons_0x0002 = { image_data_bikecompicons_0x0002, 24, 24, 35, yes};
#endif


static const tChar bikecompicons_array[] = {

#if (0x0 == 0x0)
    // character: '\x0000'
    {0x0000, &bikecompicons_0x0000},
#else
    // character: '\x0000' == ''
    {0x0000, &bikecompicons_0x},
#endif

#if (0x0 == 0x0)
    // character: '\x0001'
    {0x0001, &bikecompicons_0x0001},
#else
    // character: '\x0001' == ''
    {0x0001, &bikecompicons_0x},
#endif

#if (0x00001 == 0x0)
    // character: '\x0002'
    {0x0002, &bikecompicons_0x0002}
#else
    // character: '\x0002' == '\x0001'
    {0x0002, &bikecompicons_0x0001}
#endif

};


const tFont bikecompicons = { 3, bikecompicons_array };
